---
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-smtp
  labels:
    app: bitwarden
type: Opaque
data:
# SMTP user and password. Update also configmap.yaml to setup your email
# Needs to be base64 encoded
# Default emailUser = user@yourmail.com
# Default emailPassword = supersecret
  emailUser: dXNlckB5b3VybWFpbC5jb20=
  emailPassword: c3VwZXJzZWNyZXQ=