apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reloader

bases:
  - namespace.yaml
  - https://raw.githubusercontent.com/stakater/Reloader/v1.0.40/deployments/kubernetes/reloader.yaml
