apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etcd

resources:
  - namespace.yaml
  - secret.yaml

generators:
  - generator.yaml

patchesStrategicMerge:
  - statefulset.yaml

generatorOptions:
  disableNameSuffixHash: true
