apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./alertmanager
  - ./grafana
  - ./kube-state-metrics
  - ./node-exporter
  - ./prometheus
  - ./pushgateway

resources:
  - namespace.yaml
