galaxy_info:
  author: thedatabaseme
  description: Molecule testing role
  role_name: molecule_test_role
  company: thedatabaseme
 
  license: MIT 
 
  min_ansible_version: "2.9"
 
  platforms:
  - name: EL
    versions:
    - "8"
  - name: Ubuntu
    versions:
    - focal
 
  galaxy_tags: []
 
dependencies: []
