apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
  namespace: synology-csi
spec:
  storageClassName: synology-iscsi-storage
  dataSource:
    name: new-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi