apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syn-iscsi-test
  namespace: synology-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-iscsi-storage
