apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/reloader/base/
    repoURL: 'https://github.com/thedatabaseme/cookbooks-private.git'
    targetRevision: HEAD
    plugin:
      name: git-crypt-cm-plugin
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
