apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oracle-database-operator-system

resources:
  - https://raw.githubusercontent.com/oracle/oracle-database-operator/0.2.0/oracle-database-operator.yaml

patchesStrategicMerge:
  - deployment.yaml
