name: Renovate
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}