apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

bases:
  - https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/deploy/

resources:
  - namespace.yaml

patchesStrategicMerge:
  - deployment.yaml
  - class.yaml